services:
  web:
    image: ghcr.io/andre-moniz-morais/vibing:latest
    restart: unless-stopped
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./workspaces:/app/workspaces
      
  celery:
    image: ghcr.io/andre-moniz-morais/vibing:latest
    restart: unless-stopped
    command: celery -A vibing worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - web

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  default:
    name: docker_shared_network
    external: true