# Generated by Django 6.0.3 on 2026-03-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
